{% set version = "0.8.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-clipr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/clipr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/clipr/clipr_{{ version }}.tar.gz
  sha256: 32c2931992fbec9c31b71de3e27059f1cbb45b4b1f45fd42e0e8dbcec6de3be9

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('clipr')"           # [not win]
    - "\"%R%\" -e \"library('clipr')\""  # [win]

about:
  home: https://github.com/mdlincoln/clipr
  license: GPL-3.0-only
  summary: Simple utility functions to read from and write to the Windows, OS X, and X11 clipboards.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Type: Package
# Package: clipr
# Title: Read and Write from the System Clipboard
# Version: 0.5.0
# Authors@R:  c(person(given = "Matthew", family = "Lincoln", role = c("aut", "cre"), email = "matthew.d.lincoln@gmail.com", comment = c(ORCID = "0000-0002-4387-3384")), person(given = "Louis", family = "Maddox", role = "ctb"), person(given = "Steve", family = "Simpson", role = "ctb"), person(given = "Jennifer", family = "Bryan", role = "ctb"))
# Description: Simple utility functions to read from and write to the Windows, OS X, and X11 clipboards.
# License: GPL-3
# URL: https://github.com/mdlincoln/clipr
# BugReports: https://github.com/mdlincoln/clipr/issues
# Imports: utils
# Suggests: covr, rstudioapi (>= 0.5), testthat (>= 2.0.0)
# Encoding: UTF-8
# Language: en-US
# LazyData: TRUE
# RoxygenNote: 6.1.1
# SystemRequirements: xclip (https://github.com/astrand/xclip) or xsel (http://www.vergenet.net/~conrad/software/xsel/) for accessing the X11 clipboard
# NeedsCompilation: no
# Packaged: 2019-01-11 14:07:20 UTC; admin
# Author: Matthew Lincoln [aut, cre] (<https://orcid.org/0000-0002-4387-3384>), Louis Maddox [ctb], Steve Simpson [ctb], Jennifer Bryan [ctb]
# Maintainer: Matthew Lincoln <matthew.d.lincoln@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-01-11 14:50:02 UTC
